# Generated by Django 3.0.9 on 2020-08-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
