# Generated by Django 3.0.9 on 2020-08-13 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userID',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
