# Generated by Django 3.0.5 on 2020-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.IntegerField(default=1),
        ),
    ]
