# Generated by Django 3.0.5 on 2020-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200919_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(default=1),
        ),
    ]
