# Generated by Django 3.0.9 on 2020-08-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryname', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('unitPrice', models.FloatField()),
                ('url_image', models.CharField(max_length=250)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
