# Generated by Django 3.0.5 on 2020-08-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200810_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
