# Generated by Django 3.0.5 on 2020-08-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0004_auto_20200819_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsID', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('commentaryID', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.Client')),
            ],
        ),
    ]
