# Generated by Django 3.0.5 on 2020-08-21 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='email',
        ),
        migrations.AddField(
            model_name='commentary',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
